import os


def generate_directory_tree(project_path):

    tree = ""

    for root, dirs, files in os.walk(project_path):

        level = root.replace(project_path, "").count(os.sep)

        indent = "    " * level

        tree += f"{indent}{os.path.basename(root)}/\n"

        sub_indent = "    " * (level + 1)

        for file in files:
            tree += f"{sub_indent}{file}\n"

    return tree


def generate_context_file(
        project_name,
        project_path,
        analysis):

    os.makedirs("reports", exist_ok=True)

    file_path = (
        f"reports/{project_name}_AI_CONTEXT.md"
    )

    directory_tree = generate_directory_tree(
        project_path
    )

    markdown = f"""
# AI Repository Context

Generated By: CodeScope

Repository Name: {project_name}

---

# Repository Metadata

- Total Python Files: {analysis['summary']['total_python_files']}
- Health Score: {analysis['summary']['health_score']}
- Total Cycles: {analysis['summary']['total_cycles']}
- Total Unused Modules: {analysis['summary']['total_unused_modules']}
- Total Highly Coupled Modules: {analysis['summary']['total_highly_coupled_modules']}

---

# Repository Structure

{directory_tree}

---

# Languages Detected

{analysis['languages']}

---

# Frameworks Detected

{analysis['frameworks']}

---

# Entry Points

{analysis['entry_points']}

---

# Dependency Graph

{analysis['dependencies']}

---

# Circular Dependencies

{analysis['issues']['cycles']}

---

# Unused Modules

{analysis['issues']['unused_modules']}

---

# Highly Coupled Modules

{analysis['issues']['highly_coupled']}

---

# TODOs and FIXMEs

{analysis['todos']}

---

# Security Concerns

{analysis['security_issues']}

---

# Large Files

{analysis['large_files']}

---

# File Summaries

{analysis['file_summaries']}

---

# Architectural Issues

Analyze the following possible architectural issues:

1. Circular dependencies
2. Highly coupled modules
3. Large files
4. Unused modules
5. Security vulnerabilities
6. TODO/FIXME accumulation

---

# Instructions For AI

You are a senior software architect.

You are given a complete repository context.

Using ONLY the information provided above:

1. Explain the overall architecture.
2. Explain the execution flow step-by-step.
3. Explain the starting and ending points of the application.
4. Explain major file responsibilities.
5. Explain how dependencies interact.
6. Identify probable bugs.
7. Identify architectural weaknesses.
8. Suggest fixes for every issue found.
9. Suggest refactoring opportunities.
10. Suggest performance improvements.
11. Suggest security improvements.
12. Suggest maintainability improvements.
13. Explain data flow.
14. Explain the purpose of every major module.
15. Identify dead code.
16. Identify code smells.
17. Provide a final health assessment.

Use headings, examples, and detailed explanations wherever appropriate.

Assume no additional source code is available unless explicitly provided by the user.

Generate a comprehensive professional repository analysis report.
"""

    with open(
            file_path,
            "w",
            encoding="utf-8") as file:

        file.write(markdown)

    return file_path